### PR TITLE
npm package for raknet

### PR DESCRIPTION
**Pull request by RemiArnaud**
this adds the package.json and .npm ignore that turns this into a npm module for @sb private server. We'll need also to add build script for jenkins.

now, I don't know if we want to merge this in master or not. here's two school of thoughts:
- we keep master clean of all changes, it track exactly remote. its updated from time to time.
  
  ... well, we already broke from that model, as we have merged PR that oculus do not have
- we keep master as what we would like oculus clone to have been, with all the PRs (including new one we do) that we would like to be in the origin.
  ... in that case, those packages and build scripts should go in a separate branch that we maintain in addition to maintaining master. PRs will have to go in master and this other branch. and so forth
  - we use master as our main branch, we only merge PRs in master, so we can always filter through the PRs that we would like merged in to original github
  
  that what merging this PR would do. 

@mbarnes-sb   @krunal-patel-fl4re @kirill-korepanov-sb

Note - I'm not seeing any PR or commit from kirill in this github.. is that normal (meaning we are not making any changes to RakNet?)

### CODE REVIEW

**Comment by mbarnes-sb** [comment]
@RemiArnaud I set it up to follow your second school of thought as I consider the Oculus repo abandoned. I recreated and staged all the third party PR from the original repo that looked valuable. From those, I merged the PR that were helpful and not regressive. The remainder were assigned to Joshua and then Kirill to merge at their discretion and need. So far they have not needed any code changes. Those 3rd party PR do belong on master regardless of our own PR.

I like the idea of moving Valhalla to its own release branch and leaving master alone in case we make breaking changes that the rest of the community would not appreciate. I can make this change if you agree. Otherwise we use master branch.

**Comment by RemiArnaud** [comment]
@mbarnes-sb - please merge this PR then.
thanks

**Comment by mbarnes-sb** [comment]
@RemiArnaud , @kirill-korepanov-sb ... for this change to be picked up in VH, fl4re-ext needs a submodule pointer update PR.

**Comment by RemiArnaud** [comment]
Yes, but no need. This package enable raknet to be extracted from fl4re-ext instead.

**Pull request merged**
